name: Build all Libraries (Android)

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
            lib: cimgui
          - os: ubuntu-latest
            arch: x86_64
            lib: cimguizmo
          - os: ubuntu-latest
            arch: x86_64
            lib: cimnodes
          - os: ubuntu-latest
            arch: x86_64
            lib: cimplot
            
    steps:
    - uses: actions/checkout@v4.1.7
      with:
        repository: 'cimgui/cimgui'
        path: 'cimgui'
        submodules: true
        
    - uses: actions/checkout@v4.1.7
      if: matrix.lib == 'cimguizmo'
      with:
        repository: 'JunaMeinhold/cimguizmo'
        path: 'cimguizmo'
        submodules: true

    - uses: actions/checkout@v4.1.7
      if: matrix.lib == 'cimnodes'
      with:
        repository: 'JunaMeinhold/cimnodes'
        path: 'cimnodes'
        submodules: true

    - uses: actions/checkout@v4.1.7
      if: matrix.lib == 'cimplot'
      with:
        repository: 'JunaMeinhold/cimplot'
        path: 'cimplot'
        submodules: true

    - name: Install dependencies on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Setup Android SDK
      uses: android-actions/setup-android@v2.0.10

    - name: Install Android NDK
      run: sdkmanager --install "ndk-bundle"

    - name: Build for arm64-v8a
      run: |
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_SYSTEM_NAME=Android \
                -DCMAKE_ANDROID_NDK=$ANDROID_NDK_HOME \
                -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a \
                -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang \
                -DCMAKE_ANDROID_STL_TYPE=c++_shared \
                -DCMAKE_ANDROID_API=21 \
                -S ${{ matrix.lib }} \
                -B ${{ matrix.lib }}/build/arm64-v8a
          cmake --build ${{ matrix.lib }}/build/arm64-v8a  --config Release

    - name: Build for x86_64
      run: |
          cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_SYSTEM_NAME=Android \
                -DCMAKE_ANDROID_NDK=$ANDROID_NDK_HOME \
                -DCMAKE_ANDROID_ARCH_ABI=x86_64 \
                -DCMAKE_ANDROID_NDK_TOOLCHAIN_VERSION=clang \
                -DCMAKE_ANDROID_STL_TYPE=c++_shared \
                -DCMAKE_ANDROID_API=21 \
                -S ${{ matrix.lib }} \
                -B ${{ matrix.lib }}/build/x86_64
          cmake --build ${{ matrix.lib }}/build/x86_64 --config Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4.3.4
      with:
        name: ${{ matrix.lib }}-${{ matrix.os }}-${{ matrix.arch }}-artifacts 
        path: |
          ${{ matrix.lib }}/build/arm64-v8a/*.so
          ${{ matrix.lib }}/build/x86_64/*.so
        if-no-files-found: ignore # 'warn' or 'ignore' or 'error'
